org: bolt
repository: four

# For the changelogs:
groups:
    featured: featured
    security: security
    'new-feature': added
    'tag-bug-fix': fix
    deprecated: removed
    removed: removed
    'topic-dx': code
    'chore': code

# https://github.com/ahmadawais/Emoji-Log
groupnames:
    featured: "ğŸ‘‘ Highlighted new features"
    fix: "ğŸ› Bug fixes"
    security: "ğŸ” Security related changes"
    added: "ğŸ“¦ Additions and new features"
    removed: "ğŸšš Removals and/or deprecations"
    miscellaneous: "ğŸ› ï¸ Miscellaneous"
    tests: "ğŸ¤– Tests"
    documentation: "ğŸ“– Documentation"
    code: "âš™ï¸ Code Quality / Developer Experience"