org: bolt
repository: four

# For the changelogs:
groups:
    featured: featured
    'topic-security': security
    'new-feature': added
    deprecated: removed
    removed: removed
    'topic-dx': code
    'chore': code
    'refactor': code
    'topic-tests': tests
    'tag-bug-fix': fix
    'topic-design': design
    'tag-documentation': documentation
    'tag-enhancement': enhancement

# https://github.com/ahmadawais/Emoji-Log
groupnames:
    featured: "ğŸ‘‘ Highlighted new features"
    fix: "ğŸ› Bug fixes"
    security: "ğŸ” Security related changes"
    added: "ğŸ“¦ Additions and new features"
    removed: "ğŸšš Removals and/or deprecations"
    miscellaneous: "ğŸ› ï¸ Miscellaneous"
    tests: "ğŸ¤– Tests"
    documentation: "ğŸ“– Documentation"
    code: "âš™ï¸ Code Quality / Developer Experience"
    design: "ğŸ¨ Design / User Interface"
    enhancement: "âœ¨ Minor features and improvements"
